services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    restart: unless-stopped
    container_name: mssql-db
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer

volumes:
  mssql-data: